[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["greeting_service_2023_03_30"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "greeting_service_2023_03_30"
  org = "udyogimunasinghe"
  version = "3.1.0"

