[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["graphql_service_2023_05_02"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "graphql_service_2023_05_02"
  org = "udyogimunasinghe"
  version = "3.1.1"

